# [theme]
# primaryColor="#D0B0BF"
# backgroundColor="#1b366b"
# secondaryBackgroundColor="#457ba4"
# textColor="#ffffff"

# [theme]
# primaryColor="#5bd3ea"
# backgroundColor="#835da0"
# secondaryBackgroundColor="#bfa15a"
# textColor="#ffffff"

[theme]
base="light"
primaryColor="#dabb42"
secondaryBackgroundColor="#a979bf"
textColor="#524c4c"

